"""Per-dataset geographic metadata for the benchmark datasets.

Answers "where on Earth does this dataset's imagery come from?" for every
dataset in the registry, so the sample distribution can be mapped.

The store lives in :data:`STORE_DIR` as one JSON per dataset plus an
``index.json`` summary.  It is generated by
``experiments/scripts/extract_dataset_geography.py`` and committed, so
consumers (docs figures, the leaderboard map) never need the raw imagery.

Coverage is driven by :func:`~torchgeo_bench.datasets.list_datasets`, not by
globbing ``data/``: every registered dataset gets a record with an explicit
:attr:`GeoRecord.status`, so a newly registered dataset shows up as a missing
entry (which ``tests/test_geography.py`` fails on) rather than silently
vanishing from the map.

Three statuses:

* ``extracted`` — coordinates were read from the raw files.
* ``no_geo`` — the dataset genuinely carries no coordinates; see
  :attr:`GeoRecord.reason` and :data:`NO_GEO`.
* ``not_downloaded`` — the dataset is registered but its files are not on
  disk here, so nothing could be read.

Two coordinate sources are handled:

* **V2** — ``<root>/<name>/*.tortilla``, whose metadata frame already carries
  ``lon``/``lat`` columns (plus a place label where the source provided one).
  Metadata-only, so this is fast.
* **V1** — ``<root>/<name>/*.hdf5``, where the affine ``transform`` and
  ``crs`` live in a pickle stashed in the HDF5 attributes.  The raster origin
  is reprojected to EPSG:4326.

Extraction is deterministic: re-running against unchanged raw data reproduces
byte-identical JSON.
"""

import glob
import json
import logging
import os
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Literal

import numpy as np

from .datasets import get_bench_dataset_class, list_datasets

logger = logging.getLogger(__name__)

STORE_DIR = Path(__file__).resolve().parents[2] / "docs" / "_static" / "_dataset_geography"
INDEX_NAME = "index.json"

Status = Literal["extracted", "no_geo", "not_downloaded"]

# Datasets with no geolocation whatsoever, with the verified reason. Both were
# confirmed by inspecting the raw files; treat these as facts, not guesses.
NO_GEO: dict[str, str] = {
    "so2sat": "tortilla metadata has no lon/lat columns",
    "m-so2sat": "every sample has transform=None and crs=None",
    "resisc45": (
        "scene-classification JPEGs with no georeferencing: no sampled image "
        "carries any EXIF block, and the upstream release ships no coordinate table"
    ),
}

# Datasets that carry no geometry of their own because they are a re-split of
# another dataset's imagery. Mapped to the dataset holding the coordinates.
GEO_ALIAS: dict[str, str] = {"eurosat-spatial": "m-eurosat", "eurosat": "m-eurosat"}

BIN_RES = 0.25  # degrees; drives the zoomed-out density view
POINT_CAP = 2000  # per-dataset cap on individually plotted samples
POINT_DP = 3  # ~110 m precision, plenty for a zoomable overview map

# A V1 read failure above this share means something is structurally wrong
# (bad path, changed layout) rather than a few corrupt files.
MAX_READ_FAILURE_RATE = 0.01


@dataclass(frozen=True)
class GeoRecord:
    """Geographic footprint of one benchmark dataset.

    Attributes:
        name: Dataset identifier, as registered (e.g. ``"m-eurosat"``).
        status: ``"extracted"``, ``"no_geo"``, or ``"not_downloaded"``.
        version: Source family — ``"v1"``, ``"v2"``, or ``"torchgeo"``.
            ``None`` when nothing was read.
        n: Number of geolocated samples found.
        reason: Why there are no coordinates. Always set when *status* is
            ``"no_geo"``, otherwise ``None``.
        alias_of: Set when this dataset borrows another's geometry (see
            :data:`GEO_ALIAS`).
        bbox: ``[min_lon, min_lat, max_lon, max_lat]``, or ``None``.
        continents: Percentage of samples per continent, descending.
        bins: ``[x, y, count]`` density cells on a :data:`BIN_RES` grid, where
            ``x = floor((lon + 180) / BIN_RES)`` and
            ``y = floor((lat + 90) / BIN_RES)``.
        points: Deterministic subsample, each ``[lon, lat]`` or
            ``[lon, lat, place]``, capped at :data:`POINT_CAP`.
    """

    name: str
    status: Status
    version: str | None = None
    n: int = 0
    reason: str | None = None
    alias_of: str | None = None
    bbox: list[float] | None = None
    continents: dict[str, float] = field(default_factory=dict)
    bins: list[list[int]] = field(default_factory=list)
    points: list[list[Any]] = field(default_factory=list)

    def to_json(self) -> dict:
        """Return the JSON-serialisable form written to the store."""
        return asdict(self)

    @classmethod
    def from_json(cls, data: dict) -> "GeoRecord":
        """Rebuild a record from its stored form, ignoring unknown keys."""
        known = set(cls.__dataclass_fields__)
        return cls(**{k: v for k, v in data.items() if k in known})


# --------------------------------------------------------------------------
# GeoBench V2 (.tortilla)
# --------------------------------------------------------------------------
def _extract_v2(paths: list[str]) -> dict | None:
    """Read lon/lat (and any place labels) from a dataset's tortilla files."""
    import tacoreader

    lons: list[np.ndarray] = []
    lats: list[np.ndarray] = []
    places: list[np.ndarray] = []

    for path in sorted(paths):
        df = tacoreader.load(path)
        if "lon" not in df.columns or "lat" not in df.columns:
            return None
        # TortillaDataFrame rejects standard pandas ops -- pull plain arrays out
        # immediately rather than operating on the frame.
        lons.append(np.asarray(df["lon"], dtype=float))
        lats.append(np.asarray(df["lat"], dtype=float))
        place_col = next((c for c in ("country", "city", "rai:admin0") if c in df.columns), None)
        if place_col is not None:
            places.append(np.asarray(df[place_col], dtype=object))
        else:
            places.append(np.full(len(lons[-1]), None, dtype=object))

    lon = np.concatenate(lons)
    lat = np.concatenate(lats)
    place = np.concatenate(places)

    ok = np.isfinite(lon) & np.isfinite(lat)
    return {"lon": lon[ok], "lat": lat[ok], "place": place[ok], "version": "v2"}


# --------------------------------------------------------------------------
# GeoBench V1 (.hdf5)
# --------------------------------------------------------------------------
def _v1_origin(path: str) -> tuple[float | None, float | None, str]:
    """Return the raster origin and CRS for one V1 sample.

    The pickled metadata is a flat dict keyed by band name; band entries are
    plain dicts carrying ``transform`` (affine) and ``crs``.
    """
    import h5py

    from .datasets._v1_webdataset import _safe_unpickle

    try:
        with h5py.File(path, "r") as f:
            meta = _safe_unpickle(eval(f.attrs["pickle"]))  # GeoBench's own format.
    except Exception as exc:  # Surfaced via the failure-rate gate.
        return None, None, f"ERR {type(exc).__name__}: {exc}"

    for key, entry in meta.items():
        if key in ("label", "bands_order") or not isinstance(entry, dict):
            continue
        transform, crs = entry.get("transform"), entry.get("crs")
        if transform is None or crs is None:
            continue
        # crs is a plain str for some datasets and a rasterio CRS for others.
        if isinstance(crs, str):
            epsg = crs
        else:
            code = crs.to_epsg()
            if code is None:
                continue
            epsg = f"EPSG:{code}"
        return float(transform.c), float(transform.f), epsg

    return None, None, "NOGEO"


def _extract_v1(name: str, files: list[str], workers: int) -> dict | None:
    """Extract and reproject raster origins for every sample of a V1 dataset."""
    from pyproj import Transformer

    with ProcessPoolExecutor(max_workers=workers) as pool:
        results = list(pool.map(_v1_origin, files, chunksize=64))

    errors = [r[2] for r in results if r[0] is None and r[2].startswith("ERR")]
    if errors:
        rate = len(errors) / len(results)
        logger.warning(
            "%s: %d read errors (%.1f%%); first: %s", name, len(errors), 100 * rate, errors[0]
        )
        if rate > MAX_READ_FAILURE_RATE:
            raise RuntimeError(f"{name}: {rate:.1%} of samples failed to read; first: {errors[0]}")

    usable = [(x, y, epsg) for x, y, epsg in results if x is not None]
    if not usable:
        return None

    # Group by CRS -- m-bigearthnet spans ~6 UTM zones, m-eurosat ~3.
    by_crs: dict[str, list[tuple[float, float]]] = {}
    for x, y, epsg in usable:
        by_crs.setdefault(epsg, []).append((x, y))

    lons: list[np.ndarray] = []
    lats: list[np.ndarray] = []
    for epsg, coords in sorted(by_crs.items()):
        xs = np.array([c[0] for c in coords])
        ys = np.array([c[1] for c in coords])
        if epsg.upper() in ("EPSG:4326", "4326"):
            lons.append(xs)
            lats.append(ys)
            continue
        transformer = Transformer.from_crs(epsg, "EPSG:4326", always_xy=True)
        lon, lat = transformer.transform(xs, ys)
        lons.append(np.asarray(lon))
        lats.append(np.asarray(lat))

    lon = np.concatenate(lons)
    lat = np.concatenate(lats)
    ok = np.isfinite(lon) & np.isfinite(lat) & (np.abs(lat) <= 90) & (np.abs(lon) <= 180)
    return {
        "lon": lon[ok],
        "lat": lat[ok],
        "place": np.full(int(ok.sum()), None, dtype=object),
        "version": "v1",
    }


# --------------------------------------------------------------------------
# Continent attribution
# --------------------------------------------------------------------------
def _natural_earth_countries() -> str | None:
    """Locate the Natural Earth admin-0 shapefile, downloading if needed."""
    import cartopy.io.shapereader as shpreader

    try:
        return shpreader.natural_earth(
            resolution="110m", category="cultural", name="admin_0_countries"
        )
    except Exception as exc:  # Continents are optional enrichment.
        logger.warning("natural_earth lookup failed, skipping continents: %s", exc)
        return None


def _attribute_continents(lon: np.ndarray, lat: np.ndarray) -> Counter:
    """Spatial-join points against Natural Earth admin-0 to count continents."""
    import geopandas as gpd

    shp = _natural_earth_countries()
    if shp is None:
        return Counter()

    world = gpd.read_file(shp)[["CONTINENT", "geometry"]]
    pts = gpd.GeoDataFrame(geometry=gpd.points_from_xy(lon, lat), crs="EPSG:4326")
    joined = gpd.sjoin(pts, world, how="left", predicate="within")
    # A point can land in overlapping polygons; keep one row per point.
    joined = joined[~joined.index.duplicated(keep="first")]
    return Counter(joined["CONTINENT"].fillna("Ocean / unmatched").tolist())


# --------------------------------------------------------------------------
# Extraction
# --------------------------------------------------------------------------
def _dataset_dir(name: str) -> Path | None:
    """Return the on-disk directory for a dataset, or ``None`` if absent.

    Goes through the dataset's own ``data_root()`` so the environment
    overrides (``GEOBENCH_V2_ROOT``) are honoured.
    """
    try:
        cls = get_bench_dataset_class(name)
    except KeyError:
        return None
    root = cls.data_root()
    # V1/V2 roots are the *parent* holding per-dataset subdirectories; the
    # torchgeo wrappers point straight at their own directory.
    candidate = root / name
    if candidate.is_dir():
        return candidate
    return root if root.is_dir() else None


def _build_record(name: str, data: dict, continents: Counter) -> GeoRecord:
    """Bin, subsample, and assemble the record for one extracted dataset."""
    lon, lat = data["lon"], data["lat"]

    xi = np.floor((lon + 180.0) / BIN_RES).astype(int)
    yi = np.floor((lat + 90.0) / BIN_RES).astype(int)
    counts = Counter(zip(xi.tolist(), yi.tolist()))
    bins = [[int(x), int(y), int(c)] for (x, y), c in sorted(counts.items())]

    # Deterministic subsample so re-runs are byte-identical.
    n = len(lon)
    idx = np.linspace(0, n - 1, POINT_CAP).astype(int) if n > POINT_CAP else np.arange(n)

    place = data["place"]
    points: list[list[Any]] = []
    for j in idx.tolist():
        row: list[Any] = [round(float(lon[j]), POINT_DP), round(float(lat[j]), POINT_DP)]
        p = place[j] if j < len(place) else None
        if p is not None and not (isinstance(p, float) and np.isnan(p)):
            row.append(str(p))
        points.append(row)

    total = sum(continents.values()) or 1
    shares = {
        k: round(100.0 * v / total, 2)
        for k, v in sorted(continents.items(), key=lambda kv: (-kv[1], kv[0]))
    }

    return GeoRecord(
        name=name,
        status="extracted",
        version=data["version"],
        n=int(n),
        continents=shares,
        bins=bins,
        points=points,
        bbox=[
            round(float(lon.min()), 3),
            round(float(lat.min()), 3),
            round(float(lon.max()), 3),
            round(float(lat.max()), 3),
        ],
    )


def extract_geography(name: str, *, workers: int | None = None) -> GeoRecord:
    """Extract the geographic footprint of one registered dataset.

    Args:
        name: Registered dataset identifier.
        workers: Processes used for the V1 HDF5 scan. Defaults to
            ``min(32, os.cpu_count())``.

    Returns:
        A :class:`GeoRecord`; check :attr:`GeoRecord.status` before using the
        coordinates, since a dataset may be absent or genuinely ungeolocated.
    """
    workers = workers or min(32, os.cpu_count() or 8)

    if name in NO_GEO:
        return GeoRecord(name=name, status="no_geo", reason=NO_GEO[name])

    if name in GEO_ALIAS:
        target = GEO_ALIAS[name]
        record = extract_geography(target, workers=workers)
        if record.status != "extracted":
            return GeoRecord(
                name=name,
                status=record.status,
                reason=record.reason,
                alias_of=target,
            )
        return GeoRecord(
            **{**record.to_json(), "name": name, "alias_of": target}  # type: ignore[arg-type]
        )

    directory = _dataset_dir(name)
    if directory is None:
        return GeoRecord(
            name=name, status="not_downloaded", reason=f"no data directory for {name!r}"
        )

    tortillas = sorted(glob.glob(str(directory / "*.tortilla")))
    hdf5s = sorted(glob.glob(str(directory / "*.hdf5")))

    if tortillas:
        data = _extract_v2(tortillas)
        if data is None:
            return GeoRecord(
                name=name, status="no_geo", reason="tortilla metadata has no lon/lat columns"
            )
    elif hdf5s:
        data = _extract_v1(name, hdf5s, workers)
        if data is None:
            return GeoRecord(
                name=name, status="no_geo", reason="no sample carries a usable transform/crs"
            )
    else:
        return GeoRecord(
            name=name,
            status="not_downloaded",
            reason=f"no .tortilla or .hdf5 files under {directory}",
        )

    if len(data["lon"]) == 0:
        return GeoRecord(name=name, status="no_geo", reason="all coordinates were non-finite")

    return _build_record(name, data, _attribute_continents(data["lon"], data["lat"]))


# --------------------------------------------------------------------------
# Store I/O
# --------------------------------------------------------------------------
def _record_path(name: str, store_dir: Path | None = None) -> Path:
    return (store_dir or STORE_DIR) / f"{name}.json"


def write_record(record: GeoRecord, store_dir: Path | None = None) -> Path:
    """Write one record to the store and return its path."""
    path = _record_path(record.name, store_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(record.to_json(), sort_keys=True, separators=(",", ":")))
    return path


def build_index(store_dir: Path | None = None) -> dict:
    """Rebuild ``index.json`` from the per-dataset files and return it.

    The index carries everything needed to draw a legend and disclose
    coverage gaps without loading the bulky per-dataset point lists.
    """
    directory = store_dir or STORE_DIR
    entries = []
    for path in sorted(directory.glob("*.json")):
        if path.name == INDEX_NAME:
            continue
        record = GeoRecord.from_json(json.loads(path.read_text()))
        entries.append(
            {
                "name": record.name,
                "status": record.status,
                "version": record.version,
                "n": record.n,
                "reason": record.reason,
                "alias_of": record.alias_of,
                "bbox": record.bbox,
                "continents": record.continents,
            }
        )

    overall: Counter = Counter()
    for entry in entries:
        for continent, share in entry["continents"].items():
            overall[continent] += share * entry["n"] / 100.0
    grand = sum(overall.values()) or 1

    index = {
        "bin_res": BIN_RES,
        "point_cap": POINT_CAP,
        "datasets": entries,
        "totals": {
            "datasets": len(entries),
            "extracted": sum(1 for e in entries if e["status"] == "extracted"),
            "samples": sum(e["n"] for e in entries),
            "continents": {
                k: round(100.0 * v / grand, 2)
                for k, v in sorted(overall.items(), key=lambda kv: (-kv[1], kv[0]))
            },
        },
    }
    (directory / INDEX_NAME).write_text(json.dumps(index, sort_keys=True, separators=(",", ":")))
    return index


def load_geography(name: str, store_dir: Path | None = None) -> GeoRecord:
    """Load one dataset's record from the committed store.

    Raises:
        FileNotFoundError: If the dataset has no record yet.
    """
    path = _record_path(name, store_dir)
    if not path.exists():
        raise FileNotFoundError(
            f"No geography record for {name!r} at {path}. "
            "Run experiments/scripts/extract_dataset_geography.py to generate it."
        )
    return GeoRecord.from_json(json.loads(path.read_text()))


def list_geography(store_dir: Path | None = None) -> dict[str, GeoRecord]:
    """Load every record in the store, keyed by dataset name."""
    directory = store_dir or STORE_DIR
    if not directory.is_dir():
        return {}
    records = {}
    for path in sorted(directory.glob("*.json")):
        if path.name == INDEX_NAME:
            continue
        record = GeoRecord.from_json(json.loads(path.read_text()))
        records[record.name] = record
    return records


def missing_datasets(store_dir: Path | None = None) -> set[str]:
    """Return registered datasets that have no record yet.

    This is the extension guarantee: registering a dataset without generating
    its geography makes this non-empty, and ``tests/test_geography.py`` fails.
    """
    return set(list_datasets()) - set(list_geography(store_dir))


__all__ = [
    "GEO_ALIAS",
    "INDEX_NAME",
    "NO_GEO",
    "STORE_DIR",
    "GeoRecord",
    "build_index",
    "extract_geography",
    "list_geography",
    "load_geography",
    "missing_datasets",
    "write_record",
]
