# torchgeo ResNet-50 — fMoW RGB GASSL
# Feature dimension: 2048

_target_: torchgeo_bench.models.TorchGeoResNetBench
num_channels: 3
factory: resnet50
weights_class: ResNet50_Weights
weights_member: FMOW_RGB_GASSL
auto_resize: false
target_size: 224
name: tgeo_resnet50_fmow_gassl
