# ConvNeXtV2-Tiny (28M params)
# Feature dimension: 768
# Model: convnextv2_tiny

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: convnextv2_tiny
pretrained: true
global_pool: avg
seed: null
name: convnextv2_tiny
