# DenseNet-161 (28M params)
# Feature dimension: 2208
# Model: densenet161

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: densenet161
pretrained: true
global_pool: avg
seed: null
name: densenet161
