# DenseNet-201 (18M params)
# Feature dimension: 1920
# Model: densenet201

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: densenet201
pretrained: true
global_pool: avg
seed: null
name: densenet201
