# ResNet-34 (21M params)
# Feature dimension: 512
# Model: resnet34

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: resnet34
pretrained: true
global_pool: avg
seed: null
name: resnet34
