_target_: torchgeo_bench.models.TerraTorchTerraMindBench
backbone_name: terramind_v1_base
pretrained: true
target_size: 224
modality: S2L2A
name: tt_terramind_v1_base
eval:
  segmentation:
    layers: ["encoder.11", "encoder.8", "encoder.5", "encoder.2"]
    use_layer_norm: true
