# EfficientNet-B1 (7M params)
# Feature dimension: 1280
# Model: efficientnet_b1

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: efficientnet_b1
pretrained: true
global_pool: avg
seed: null
name: efficientnet_b1
auto_resize: true
