# Swin-Base Patch4 Window7 224
# Feature dimension: 1024
# Model: swin_base_patch4_window7_224

_target_: src.models.TimmPatchBenchModel
num_channels: 3
model_name: swin_base_patch4_window7_224
pretrained: true
global_pool: avg
seed: null
name: swin_base_patch4_window7_224
