# DeiT-Tiny Patch16 224
# Feature dimension: 192
# Model: deit_tiny_patch16_224

_target_: torchgeo_bench.models.TimmPatchBenchModel
model_name: deit_tiny_patch16_224
pretrained: true
global_pool: avg
seed: null
name: deit_tiny_patch16_224
use_cls_token: false
