# Swin-Tiny Patch4 Window7 224
# Feature dimension: 768
# Model: swin_tiny_patch4_window7_224

_target_: torchgeo_bench.models.TimmPatchBenchModel
model_name: swin_tiny_patch4_window7_224
pretrained: true
global_pool: avg
seed: null
name: swin_tiny_patch4_window7_224
