# SwinV2-Tiny Window8 256 (28M params)
# Feature dimension: 768
# Model: swinv2_tiny_window8_256

_target_: torchgeo_bench.models.TimmPatchBenchModel
num_channels: 3
model_name: swinv2_tiny_window8_256
pretrained: true
global_pool: avg
seed: null
name: swinv2_tiny_window8_256
auto_resize: true
