# ViT-Base Patch16 224
# Feature dimension: 768
# Model: vit_base_patch16_224

_target_: torchgeo_bench.models.TimmPatchBenchModel
model_name: vit_base_patch16_224
pretrained: true
global_pool: avg
seed: null
name: vit_base_patch16_224
use_cls_token: false
