# ConvNeXt-Small (50M params)
# Feature dimension: 768
# Model: convnext_small

_target_: torchgeo_bench.models.TimmPatchBenchModel
num_channels: 3
model_name: convnext_small
pretrained: true
global_pool: avg
seed: null
name: convnext_small
