# DenseNet-201 (18M params)
# Feature dimension: 1920
# Model: densenet201

_target_: torchgeo_bench.models.TimmPatchBenchModel
model_name: densenet201
pretrained: true
global_pool: avg
seed: null
name: densenet201
