# EfficientNet-B3 (12M params)
# Feature dimension: 1536
# Model: efficientnet_b3

_target_: torchgeo_bench.models.TimmPatchBenchModel
num_channels: 3
model_name: efficientnet_b3
pretrained: true
global_pool: avg
seed: null
name: efficientnet_b3
auto_resize: true
