# RegNetX-002 (2.7M params)
# Feature dimension: 368
# Model: regnetx_002

_target_: torchgeo_bench.models.TimmPatchBenchModel
num_channels: 3
model_name: regnetx_002
pretrained: true
global_pool: avg
seed: null
name: regnetx_002
