name: benv2
task: classification
num_classes: 19
sensor: sentinel-2+sar
version: v2
v2_class: GeoBenchBENV2
rgb_bands:
- b04
- b03
- b02
bands:
- name: B01
  short: b01
  wavelength_um: 0.443
  mean: 355.962
  std: 512.342
- name: B02
  short: b02
  wavelength_um: 0.49
  mean: 414.3731
  std: 541.9492
- name: B03
  short: b03
  wavelength_um: 0.56
  mean: 594.0964
  std: 532.5798
- name: B04
  short: b04
  wavelength_um: 0.665
  mean: 559.0434
  std: 607.0201
- name: B05
  short: b05
  wavelength_um: 0.705
  mean: 919.41
  std: 646.3411
- name: B06
  short: b06
  wavelength_um: 0.74
  mean: 1794.6605
  std: 1041.3501
- name: B07
  short: b07
  wavelength_um: 0.783
  mean: 2091.4595
  std: 1231.7878
- name: B08
  short: b08
  wavelength_um: 0.842
  mean: 2241.5178
  std: 1340.4662
- name: B8A
  short: b8a
  wavelength_um: 0.865
  mean: 2288.0303
  std: 1316.0288
- name: B09
  short: b09
  wavelength_um: 0.945
  mean: 2289.5381
  std: 1267.3955
- name: B11
  short: b11
  wavelength_um: 1.61
  mean: 1556.9587
  std: 984.2933
- name: B12
  short: b12
  wavelength_um: 2.19
  mean: 973.8273
  std: 753.2082
- name: VV
  short: vv
  mean: -18.9633
  std: 5.3961
- name: VH
  short: vh
  mean: -12.0919
  std: 4.5749
