name: forestnet
task: classification
num_classes: 12
sensor: sentinel-2
version: v2
v2_class: GeoBenchForestnet
rgb_bands:
- b04
- b03
- b02
bands:
- name: B02
  short: b02
  wavelength_um: 0.49
  mean: 72.3759
  std: 16.2839
- name: B03
  short: b03
  wavelength_um: 0.56
  mean: 83.1816
  std: 15.3587
- name: B04
  short: b04
  wavelength_um: 0.665
  mean: 77.0861
  std: 16.6665
- name: B8A
  short: b8a
  wavelength_um: 0.865
  mean: 123.5425
  std: 16.9485
- name: B11
  short: b11
  wavelength_um: 1.61
  mean: 91.0483
  std: 14.2801
- name: B12
  short: b12
  wavelength_um: 2.19
  mean: 74.3097
  std: 13.2854
