name: fotw
task: segmentation
num_classes: 4
sensor: sentinel-2
version: v2
v2_class: GeoBenchFieldsOfTheWorld
rgb_bands:
- red
- green
- blue
bands:
- name: red
  short: red
  mean: 862.084
  std: 681.1667
- name: green
  short: green
  mean: 853.3895
  std: 508.6401
- name: blue
  short: blue
  mean: 592.008
  std: 454.0239
- name: nir
  short: nir
  mean: 2984.3018
  std: 1043.6527
