name: m-brick-kiln
task: classification
num_classes: 2
sensor: sentinel-2
version: v1
rgb_bands:
- red
- green
- blue
bands:
- name: 01 - Coastal aerosol
  short: coastal_aerosol
  wavelength_um: 0.443
  mean: 574.76
  std: 193.61
- name: 02 - Blue
  short: blue
  wavelength_um: 0.49
  mean: 674.35
  std: 238.75
- name: 03 - Green
  short: green
  wavelength_um: 0.56
  mean: 886.37
  std: 276.96
- name: 04 - Red
  short: red
  wavelength_um: 0.665
  mean: 815.09
  std: 361.15
- name: 05 - Vegetation Red Edge
  short: red_edge_1
  wavelength_um: 0.705
  mean: 1128.81
  std: 364.59
- name: 06 - Vegetation Red Edge
  short: red_edge_2
  wavelength_um: 0.74
  mean: 1934.45
  std: 724.27
- name: 07 - Vegetation Red Edge
  short: red_edge_3
  wavelength_um: 0.783
  mean: 2045.77
  std: 819.65
- name: 08 - NIR
  short: nir
  wavelength_um: 0.842
  mean: 2012.74
  std: 794.37
- name: 08A - Vegetation Red Edge
  short: red_edge_4
  wavelength_um: 0.865
  mean: 1608.63
  std: 800.85
- name: 09 - Water vapour
  short: water_vapour
  wavelength_um: 0.945
  mean: 1129.82
  std: 704.02
- name: 10 - SWIR - Cirrus
  short: swir_cirrus
  wavelength_um: 1.375
  mean: 83.27
  std: 36.36
- name: 11 - SWIR
  short: swir_1
  wavelength_um: 1.61
  mean: 90.55
  std: 28.0
- name: 12 - SWIR
  short: swir_2
  wavelength_um: 2.19
  mean: 68.99
  std: 24.27
