name: m-eurosat
task: classification
num_classes: 10
sensor: sentinel-2
version: v1
rgb_bands:
- red
- green
- blue
bands:
- name: 01 - Coastal aerosol
  short: coastal_aerosol
  wavelength_um: 0.443
  mean: 1356.78
  std: 246.34
- name: 02 - Blue
  short: blue
  wavelength_um: 0.49
  mean: 1123.14
  std: 334.28
- name: 03 - Green
  short: green
  wavelength_um: 0.56
  mean: 1057.28
  std: 392.23
- name: 04 - Red
  short: red
  wavelength_um: 0.665
  mean: 959.18
  std: 590.94
- name: 05 - Vegetation Red Edge
  short: red_edge_1
  wavelength_um: 0.705
  mean: 1227.44
  std: 548.57
- name: 06 - Vegetation Red Edge
  short: red_edge_2
  wavelength_um: 0.74
  mean: 2076.63
  std: 843.08
- name: 07 - Vegetation Red Edge
  short: red_edge_3
  wavelength_um: 0.783
  mean: 2463.43
  std: 1071.73
- name: 08 - NIR
  short: nir
  wavelength_um: 0.842
  mean: 2390.32
  std: 1106.87
- name: 08A - Vegetation Red Edge
  short: red_edge_4
  wavelength_um: 0.865
  mean: 761.55
  std: 404.41
- name: 09 - Water vapour
  short: water_vapour
  wavelength_um: 0.945
  mean: 12.33
  std: 5.08
- name: 10 - SWIR - Cirrus
  short: swir_cirrus
  wavelength_um: 1.375
  mean: 1861.29
  std: 963.03
- name: 11 - SWIR
  short: swir_1
  wavelength_um: 1.61
  mean: 1138.94
  std: 742.79
- name: 12 - SWIR
  short: swir_2
  wavelength_um: 2.19
  mean: 2699.78
  std: 1215.04
