name: m-pv4ger
task: classification
num_classes: 2
sensor: aerial
version: v1
rgb_bands:
- red
- green
- blue
bands:
- name: Blue
  short: blue
  mean: 116.63
  std: 44.67
- name: Green
  short: green
  mean: 119.66
  std: 48.28
- name: Red
  short: red
  mean: 113.39
  std: 54.2
