name: spacenet2
task: segmentation
num_classes: 3
sensor: worldview
version: v2
v2_class: GeoBenchSpaceNet2
rgb_bands:
- red
- green
- blue
bands:
- name: coastal
  short: coastal
  mean: 298.7281
  std: 106.9792
- name: blue
  short: blue
  mean: 358.0099
  std: 148.1868
- name: green
  short: green
  mean: 464.5104
  std: 224.4095
- name: yellow
  short: yellow
  mean: 419.9473
  std: 225.7901
- name: red
  short: red
  mean: 333.6004
  std: 194.0233
- name: red_edge
  short: red_edge
  mean: 408.6689
  std: 208.4557
- name: nir1
  short: nir1
  mean: 475.0842
  std: 234.7585
- name: nir2
  short: nir2
  mean: 362.3487
  std: 193.2321
- name: pan
  short: pan
  mean: 468.574
  std: 260.8954
